# .github/workflows/package-scan-lambda.yml
name: Package Scan With Serverless Lambda
run-name: ${{ github.actor }} is performing package vulnerability scans and ephemeral testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: tf-ephemeral-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is automatically triggered by a ${{ github.event_name }} event."

  terraform-checks:
    runs-on: ubuntu-latest
    needs: [pre-deploy]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Initialize Terraform (Modules Only)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate -no-color

  package-scan-npm-audit:
    runs-on: ubuntu-latest
    needs: terraform-checks
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run installation of dependencies
        run: |
          npm ci --package-lock-only || npm install --package-lock-only
      - name: Run audit
        run: npm audit --audit-level=high

  snyk-scans:
    runs-on: ubuntu-latest
    needs: terraform-checks
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Open Source Test (SCA)
        run: snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Infrastructure as Code Test (IaC)
        run: snyk iac test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  terraform-create:
    needs: [package-scan-npm-audit, snyk-scans]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init

      - name: Terraform Plan & Apply
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

  terraform-wait:
    needs: terraform-create
    runs-on: ubuntu-latest
    steps:
      - name: Pause 2min to verify lambda creation and test
        run: sleep 120

  terraform-destroy:
    needs: terraform-wait
    runs-on: ubuntu-latest
    if: always() && needs.terraform-create.result == 'success'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Terraform init
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy -auto-approve